### ISSUE TITLE
Newline/Break in variable not working.

### ISSUE THREAD

**Issue by xeroxoid** [yads/nodemailer-express-handlebars#1]
Hi! Excellent plug in! I could not find a way to insert a newline or a break per se in a variable. As it seems that `<br />` or `<br>` are being escaped on compilation and `\n` needs something like this http://stackoverflow.com/questions/12331077/does-handlebars-js-replace-newline-characters-with-br I suppose to work (but could not figure out how to apply such a helper without requiring handlebars.

**Comment by yads** [comment]
You should be able to specify the helpers in the options like so:

```
transporter.use('compile', hbs({
  viewEngine: {
    helpers: {
      breakLines: function(text) { ... }
    }
  }
}));
```

Alternatively you can create the express-handlebars instance, specify helpers on that and pass that instance as the viewEngine. See https://github.com/yads/nodemailer-express-handlebars#plugin-options

**Comment by xeroxoid** [comment]
~~I still do not understand why `<br>` is rendered and not replaced with a proper break.~~

Ok just replace {{text}} with {{{text}}} and html tags are not escaped. (tripple braces, much simpler imo)
