### ISSUE TITLE
What is the correct way to work with embedded images?

### ISSUE THREAD

**Issue by dtemes** [yads/nodemailer-express-handlebars#12]
Is there a way to automatically handle images used in the html templates? The only way I have managed to get them to show in the email is by attaching them to the nodemailer message object and reference the cid in the html template. having to attach the image files in the node code is less than optimal:

js:
```

var attachments = [
    {
      filename: 'logo.png',
      path: 'templates/images/logo.png',
      cid: 'logo.png'
    }
];

var message = {
      from: 'noreply@example.com',
      to: email,
      subject: 'Test message',
      template: 'template',
      context: {
       name: "Test user"
      },
      attachments: attachments
  };

}
```

html template.hbs:
...
`<img src="cid:logo.png">`
...

It would be nice to have some full ussage examples.

**Comment by yads** [comment]
That is how nodemailer handles attachments. This is just a utility library that allows using handlebars templates with nodemailer. See the guide here https://community.nodemailer.com/using-embedded-images/
