### ISSUE TITLE
Template variables in subject line

### ISSUE THREAD

**Issue by knoxcard** [yads/nodemailer-express-handlebars#14]
I'e found the need to include template variables into the subject line of the email.

**For Example...**
"Hello Bob, here is your update...."
"Hello {{first_name}}, here is your update..."

Don't know if the currentversions already support this or not, if so, this ticket can be closed.
I wrote a code as a workaround a while back ago that allows the subject line to access any template variable.  If this isn't supported yet, I can create a pull request when the time arises.

` subject: require('html-entities').AllHtmlEntities.decode(require('handlebars').compile(notif_rec.subject)(obj.template_vars))`

**Comment by knoxcard** [comment]
Submitted pull request, over and out...

**Comment by yads** [comment]
Hey see my comment in #16
