### ISSUE TITLE
inline css and image

### ISSUE THREAD

**Issue by derit** [yads/nodemailer-express-handlebars#20]
how to include image and css inline for template?

**Comment by yads** [comment]
See this in the nodemailer documentation: https://community.nodemailer.com/using-embedded-images/

**Comment by derit** [comment]
for inline css?

**Comment by yads** [comment]
I mean for CSS, you can just include it in the hbs template can you not? Can you post an example of what you're trying to do if this doesn't help?

**Comment by tuffant21** [comment]
For this, I think he means doing something similar to this: https://www.npmjs.com/package/inline-css. When sending emails, it seems that you don't want any style tags. Instead, they should be converted to inline css as explained here: https://www.mailgun.com/blog/transactional-html-email-templates/
** Note, the library (premailer) for inlining css doens't seem to work all that great. That is why I linked the inline-css package above. It seems to work better.

Is there a way to inline css styles using this library?
