### ISSUE TITLE
“A partials dir must be a string or config object” using nodemailer-express-handlebars in Firebase Functions

### ISSUE THREAD

**Issue by Tomdrouv1** [yads/nodemailer-express-handlebars#22]
Hi,

I'm facing an issue for 2 weeks now when I'm using this library in my project hosted in Firebase.

This function works well in local environment and worked well before but now this issue appears, like if my path in the handlebars configuration disappears.

```javascript
mailTransport.use('compile', hbs({viewEngine: '.handlebars', viewPath: templateDir}));
```
templateDir is a string of course but in the Firebase Functions console the issue “A partials dir must be a string or config object” appears.

Any idea of what it may be?

Thanks

**Comment by neon-sombrero** [comment]
I'm seeing this also. Looks like there was a change in `express-handlebars` which `nodemailer-express-handlebars` depends on. See [here](https://github.com/ericf/express-handlebars/commit/9e6df75db1e5853e78e8ecb38411c62a4b263ae3#diff-04c6e90faac2675aa89e2176d2eec7d8R188).

**Comment by neon-sombrero** [comment]
I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:

```
const handlebarOptions = {
  viewEngine: {
    extName: '.hbs',
    partialsDir: 'some/path',
    layoutsDir: 'some/path',
    defaultLayout: 'email.body.hbs',
  },
  viewPath: 'some/path',
  extName: '.hbs',
};

transporter.use('compile', hbs(handlebarOptions));
```

The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

**Comment by GahFlorencio** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

Works for me thanks a lot now the partialsDir is required i just put it on code and BANG worked ! , thanks again !

**Comment by roxdavirox** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

works for me using partialsDir, thanks

**Comment by Jeirsen** [comment]
Anyone solve this?, 

Im trying to use this workaround but mailer keep using default index instead of the template that i send it

const handlebarOptions = {
      viewEngine: {
        extName: ".hbs",
        partialsDir: path.resolve("./views/partials"),
        layoutsDir: path.resolve("./views"),
        defaultLayout: "index.hbs"
      },
      viewPath: path.resolve("./templates"),
      extName: ".html"
    };

**Comment by richard4s** [comment]
Incase anyone wonders why it still doesn't work, check out this last line, take note of the hbs function
**`transporter.use('compile', hbs(handlebarOptions));`** and change it to mailerhbs
**`transporter.use('compile', mailerhbs(handlebarOptions));`**

**Comment by denisgianne** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> 
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

Works for me too, using the partialDir. Thanks!

**Comment by denisgianne** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> 
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

Works for me too, using the partialDir. Thanks!

**Comment by aman-anand** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> 
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

works

**Comment by 1510143** [comment]
> I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: 'email.body.hbs',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> 
> transporter.use('compile', hbs(handlebarOptions));
> ```
> 
> The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.

It works. But when I used different template to send email. The default template still used.
My code:
```
var handlebarsOptions = {
    viewEngine: {
        extName: '.html',
        partialsDir: path.resolve('./views/templates/'),
        layoutsDir: path.resolve('./views/templates/'),
        defaultLayout: 'forgot-password-email.html',
    },
    viewPath: path.resolve('./views/templates/'),
    extName: '.html'
};
smtpTransport.use('compile', hbs(handlebarsOptions));
var data = {
                            from: process.env.EMAIL,
                            to: user.email,
                            template: 'reset-password-success-email',
                            subject: 'Password Reset Confirmation',
                            context: {
                                name: user.name
                            }
                        };
smtpTransport.sendMail(data);
```
Please help.

**Comment by amr3mmar** [comment]
> > I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> > ```
> > const handlebarOptions = {
> >   viewEngine: {
> >     extName: '.hbs',
> >     partialsDir: 'some/path',
> >     layoutsDir: 'some/path',
> >     defaultLayout: 'email.body.hbs',
> >   },
> >   viewPath: 'some/path',
> >   extName: '.hbs',
> > };
> > 
> > transporter.use('compile', hbs(handlebarOptions));
> > ```
> > 
> > 
> > The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.
> 
> It works. But when I used different template to send email. The default template still used.
> My code:
> 
> ```
> var handlebarsOptions = {
>     viewEngine: {
>         extName: '.html',
>         partialsDir: path.resolve('./views/templates/'),
>         layoutsDir: path.resolve('./views/templates/'),
>         defaultLayout: 'forgot-password-email.html',
>     },
>     viewPath: path.resolve('./views/templates/'),
>     extName: '.html'
> };
> smtpTransport.use('compile', hbs(handlebarsOptions));
> var data = {
>                             from: process.env.EMAIL,
>                             to: user.email,
>                             template: 'reset-password-success-email',
>                             subject: 'Password Reset Confirmation',
>                             context: {
>                                 name: user.name
>                             }
>                         };
> smtpTransport.sendMail(data);
> ```
> 
> Please help.

I had the same issue, just set the  defaultLayout to an empty string and it'll depend on the template in the mailoptions: 
```
const handlebarOptions = {
  viewEngine: {
    extName: '.hbs',
    partialsDir: 'some/path',
    layoutsDir: 'some/path',
    defaultLayout: '',
  },
  viewPath: 'some/path',
  extName: '.hbs',
};
```

transporter.use('compile', hbs(handlebarOptions));

**Comment by Ber1984** [comment]
> 
> 
> > I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> > ```
> > const handlebarOptions = {
> >   viewEngine: {
> >     extName: '.hbs',
> >     partialsDir: 'some/path',
> >     layoutsDir: 'some/path',
> >     defaultLayout: 'email.body.hbs',
> >   },
> >   viewPath: 'some/path',
> >   extName: '.hbs',
> > };
> > 
> > transporter.use('compile', hbs(handlebarOptions));
> > ```
> > 
> > 
> > The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.
> 
> Works for me too, using the partialDir. Thanks!

Hi can you show me what you put in the viewPath on your project?

**Comment by LeTranAnhVu** [comment]
> > > I managed to get my code working, posting in case it helps out. I had to add the `partialsDir` to my `handlebarOptions` where I didn't have the field before:
> > > ```
> > > const handlebarOptions = {
> > >   viewEngine: {
> > >     extName: '.hbs',
> > >     partialsDir: 'some/path',
> > >     layoutsDir: 'some/path',
> > >     defaultLayout: 'email.body.hbs',
> > >   },
> > >   viewPath: 'some/path',
> > >   extName: '.hbs',
> > > };
> > > 
> > > transporter.use('compile', hbs(handlebarOptions));
> > > ```
> > > 
> > > 
> > > The `partialsDir` must have been an optional field at one point, but now seems to be required. Hope this helps.
> > 
> > 
> > It works. But when I used different template to send email. The default template still used.
> > My code:
> > ```
> > var handlebarsOptions = {
> >     viewEngine: {
> >         extName: '.html',
> >         partialsDir: path.resolve('./views/templates/'),
> >         layoutsDir: path.resolve('./views/templates/'),
> >         defaultLayout: 'forgot-password-email.html',
> >     },
> >     viewPath: path.resolve('./views/templates/'),
> >     extName: '.html'
> > };
> > smtpTransport.use('compile', hbs(handlebarsOptions));
> > var data = {
> >                             from: process.env.EMAIL,
> >                             to: user.email,
> >                             template: 'reset-password-success-email',
> >                             subject: 'Password Reset Confirmation',
> >                             context: {
> >                                 name: user.name
> >                             }
> >                         };
> > smtpTransport.sendMail(data);
> > ```
> > 
> > 
> > Please help.
> 
> I had the same issue, just set the defaultLayout to an empty string and it'll depend on the template in the mailoptions:
> 
> ```
> const handlebarOptions = {
>   viewEngine: {
>     extName: '.hbs',
>     partialsDir: 'some/path',
>     layoutsDir: 'some/path',
>     defaultLayout: '',
>   },
>   viewPath: 'some/path',
>   extName: '.hbs',
> };
> ```
> 
> transporter.use('compile', hbs(handlebarOptions));

It did work. Thanks
