### ISSUE TITLE
HIGH SEVERITY vulnerability [snyk] express prototype pollution [security] #250

### ISSUE THREAD

**Issue by iwaduarte** [yads/nodemailer-express-handlebars#24]
https://github.com/ericf/express-handlebars/issues/250
Is there any chance to replace them with the hbs module ?
https://github.com/pillarjs/hbs
I have pointed out the security flaw 2 days ago in these two packages and one corrected (the one I am using for  my application (hbs)) and this one who did not bother answering.

Is there anything you could do it to fix this? Cheers

**Comment by yads** [comment]
So to replace express-handlebars with hbs? Let me take a look.

**Comment by yads** [comment]
Actually looks like express-handlebars has been updated. I'll update the dependencies and push out a release.

**Comment by yads** [comment]
Updated express-handlebars dependency and published version 3.1.0
