### ISSUE TITLE
Different Layouts?

### ISSUE THREAD

**Issue by ghost** [yads/nodemailer-express-handlebars#3]
The options allows you to specify a default layout, but there is no parameter when sending the mail to specify the layout? How would I use this with different layouts?

**Comment by yads** [comment]
The context object that is part of the options you pass to the sendMail method, acts as the options parameter in [renderView](https://github.com/ericf/express-handlebars#renderviewviewpath-optionscallback-callback). So you can specify the layout as part of an options object.

**Comment by bernlorbis** [comment]
> The context object that is part of the options you pass to the sendMail method, acts as the options parameter in [renderView](https://github.com/ericf/express-handlebars#renderviewviewpath-optionscallback-callback). So you can specify the layout as part of an options object.

This is not working

**Comment by yads** [comment]
This is an 8 year old bug. If this is not working please open a new ticket with the exact call that is not working.
