### ISSUE TITLE
Tries to open main.hbs while template equals welcome.hbs

### ISSUE THREAD

**Issue by ismail-codinglab** [yads/nodemailer-express-handlebars#30]
Hi,

since using version 3.1.0 I get the following problem

`Error: ENOENT: no such file or directory, open '/.../main.hbs'`

The problem is not that it cannot find `main.hbs` it is that it should open `welcome.hbs` but it tries to open `main.hbs` i got no other error to debug it.

When i log the `mail.data.template` it does refer to `welcome.hbs`. And yes `welcome.hbs` exists, and yes it's in the correct directory. How do i know this? When i add main.hbs in the same directory as welcome.hbs it can find main.hbs and sends main.hbs email.

![image](https://user-images.githubusercontent.com/48755937/65180224-a618cb80-da5c-11e9-8c67-e0250767b741.png)

The versions i'm using:
nodemailer@6.3.0
nodemailer-express-handlebars@3.1.0

**Comment by masonmonu** [comment]
Hi @Ismail-codinglab ,
I was also gone through the same issue, just put following line inside viewEngine object will resolve the issue.

defaultLayout:false

**Comment by yads** [comment]
Thanks @masonmonu
