### ISSUE TITLE
Handlebars: Access has been denied to resolve the property "author" because it is not an "own property" of its parent. You can add a runtime option to disable the check or this warning: See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details

### ISSUE THREAD

**Issue by Wennlys** [yads/nodemailer-express-handlebars#35]
**I've already to read Handlebars's documentation and topic about this problem but I didn't find anything related with nodemailer-express-handlebars**
```

**Mail.js** = const path = require('path')
const nodemailer = require('nodemailer')
const handlebars = require('express-handlebars')
const hbs = require('nodemailer-express-handlebars')

const mailConfig = require('../../config/mail')

const transport = nodemailer.createTransport(mailConfig)

const viewPath = path.resolve(__dirname, '..', 'views', 'mails')

transport.use(
  'compile',
  hbs({
    viewEngine: handlebars.create({
      partialsDir: path.resolve(viewPath, 'partials')
    }),
    viewPath,
    extName: '.hbs'
  })
)

module.exports = transport

----------------------------------------------------------------------------------------------------------------
**PurchaseControlelr that uses 'Main.js'** = `class PurchaseController {
  async store(req, res) {
    const { ad, content } = req.body

    const purchaseAd = await Ad.findById(ad).populate('author')
    const user = await User.findById(req.userId)

    await Mail.sendMail({
      from: '"Wennlys Oliveira" <wennlys@gmail.com>',
      to: purchaseAd.author.email,
      subject: `Purchase solicitation: ${purchaseAd.title}`,
      template: 'purchase',
      context: { user, content, ad: purchaseAd }
    })

    return res.send()
  }
}



```

**Comment by yads** [comment]
This seems to be an issue with handlebars itself.

**Comment by adoidadox2** [comment]
filhoda puta

**Comment by adoidadox2** [comment]
> **I've already to read Handlebars's documentation and topic about this problem but I didn't find anything related with nodemailer-express-handlebars**
> 
> ```
> 
> **Mail.js** = const path = require('path')
> const nodemailer = require('nodemailer')
> const handlebars = require('express-handlebars')
> const hbs = require('nodemailer-express-handlebars')
> 
> const mailConfig = require('../../config/mail')
> 
> const transport = nodemailer.createTransport(mailConfig)
> 
> const viewPath = path.resolve(__dirname, '..', 'views', 'mails')
> 
> transport.use(
>   'compile',
>   hbs({
>     viewEngine: handlebars.create({
>       partialsDir: path.resolve(viewPath, 'partials')
>     }),
>     viewPath,
>     extName: '.hbs'
>   })
> )
> 
> module.exports = transport
> 
> ----------------------------------------------------------------------------------------------------------------
> **PurchaseControlelr that uses 'Main.js'** = `class PurchaseController {
>   async store(req, res) {
>     const { ad, content } = req.body
> 
>     const purchaseAd = await Ad.findById(ad).populate('author')
>     const user = await User.findById(req.userId)
> 
>     await Mail.sendMail({
>       from: '"Wennlys Oliveira" <wennlys@gmail.com>',
>       to: purchaseAd.author.email,
>       subject: `Purchase solicitation: ${purchaseAd.title}`,
>       template: 'purchase',
>       context: { user, content, ad: purchaseAd }
>     })
> 
>     return res.send()
>   }
> }
> ```

@Wennlys Tive o mesmo problema, depois de muitas pesquisas e testes. Consegui resolver 
assim -

Adiciona essas duas dependências: 

`yarn add @handlebars/allow-prototype-access `
`yarn add handlebars`    

Deixa assim o Mail.js: 

![Captura de tela](https://user-images.githubusercontent.com/39576148/80319883-57e55b00-87e9-11ea-9dbe-b1efefe711b7.png)

Deixa a estrutura da pasta views assim: 

![captura](https://user-images.githubusercontent.com/39576148/80319924-8bc08080-87e9-11ea-8926-d8e98b92cb6b.png)

Copia todo o código do `purchase.hbs` e cola no arquivo `main.handlebars`

Essa provavelmente não é nem de longe a maneira correta de resolver esse problema, mas foi a única que eu encontrei pra mim.
