### ISSUE TITLE
(node:1444) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by nithin-pb** [yads/nodemailer-express-handlebars#37]
Can somebody help me on this issue?

I defined my template name but still getting this path or file not found,

(node:1444) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\nithin\Documents\nodeTest\API\views\**undefined.**handlebars'
(node:1444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an 
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

here is the of code  
`sentMail:(_email)=>{
        let transporter = nodemailer.createTransport({
            service:'gmail',
            auth: {
              user: 'xxxxxxxx@gmail.com', 
              pass: 'xxxxxxxx' 
            }
          });

          transporter.use('compile',hbs({
            viewEngine: {
              extName: '.handlebars',
              partialsDir: './views/',
              layoutsDir: './views/',
              defaultLayout: 'home.handlebars',
            },
            viewPath: './views/',
            extName: '.handlebars'
          }));

          let mailOptions = {
            from: '"TEST " <xxx@xxx.com>', 
            to: _email, // list of receivers
            subject: "Verify your Email Id", 
            template:'home'
          }
            // send mail with defined transport object
            let info = transporter.sendMail({mailOptions
            });`

**Comment by yads** [comment]
Does the answer in https://github.com/yads/nodemailer-express-handlebars/issues/36 help?

**Comment by carlocorradini** [comment]
@nithinpachday In [partialsDir, layoutsDir, viewPath] try to use **path.join** in combination with **__dirname**.

Use **defaultLayout: false** since It creates some problems.

Here Is the code:

```javascript
import path from 'path'

transporter.use('compile', hbs({
  viewEngine: {
      extName: '.handlebars',
      partialsDir: path.join(__dirname, 'views/'),
      layoutsDir: path.join(__dirname, 'views/'),
      defaultLayout: false,
  },
  viewPath: path.join(__dirname, 'views/'),
  extName: '.handlebars'
}));
```

Hope It helps:wink:

**Comment by nithin-pb** [comment]
I modified the code like this. Thanks @carlocorradini Thanks @yads 


`const nodemailer = require("nodemailer");
const hbs = require('nodemailer-express-handlebars');
module.exports = {
    sentMail: (_email, _type, _username) => {
        let transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: 'xxx@xxx.xom',
                pass: 'xxxxxxxxxxxxx'
            }
        });

        transporter.use('compile', hbs({
            viewEngine: {
                layoutsDir: './email/views',
                defaultLayout: _type,
                partialsDir: './email/views'
            },
            viewPath: './email/views'
        }));

        var mailOptions = {
            from: 'Gamliot Community <gamliot.it@gmail.com>',
            to: _email,
            subject: 'Gamliot Community Team',
            template: _type,
            context:{
              userName:_username,
            }
        }

        transporter.sendMail(mailOptions, function(err, info) {
            if (err) {
                //handle error here
                console.log(err);
            } else {
                //handle success here
                console.log(info);
            }
        });
    }
};`
