### ISSUE TITLE
Error: ENOENT: no such file or directory for template

### ISSUE THREAD

**Issue by emarel** [yads/nodemailer-express-handlebars#43]
I am having an issue where nodemailer-express-handlebars is outputting the error:

```
[Error: ENOENT: no such file or directory, open '/Users/person/Code/app/templates/undefined.hbs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/person/Code/app/templates/undefined.hbs'
```

My setup is as follows (using advice/solution from a previous [post]( https://github.com/yads/nodemailer-express-handlebars/issues/26) from @nbrookie)

```
 const handlebarOptions = {
    viewEngine: {
      extName: ".hbs",
      partialsDir: path.resolve(__dirname, "templates"),
      defaultLayout: false
    },
    viewPath: path.resolve(__dirname, "templates"),
    extName: ".hbs"
  };

  transporter.use('compile', hbs(handlebarOptions));
```

and sending the email with:

```
let mailOptions = await transporter.sendMail({
    from: '"Test - No Reply" <test@test.com>'
    to: 'someEmail@gmail.com, 
    subject: "Hello ✔",
    template: 'welcome',
  });
```

Oddly enough I still receive the email even though it says it cant find the file. How is this possible and how can I resolve this issue?

**Comment by nachiketkallapur** [comment]
Even I'm getting same error but error number is "-4058"

**Comment by emarel** [comment]
> Even I'm getting same error but error number is "-4058"

Also interesting to note...

I changed 'welcome' to 'welcome.hbs' in the nodemailer and now the error is saying it can't find 'welcome.hbs.hbs'. This makes sense, you would think the solution would be to remove the '.hbs' and make it 'welcome' but then we are back to the original error of 'undefined.hbs'.

Also, if i change the template to 'welcome2' it says it cant find 'welcome2.hbs'. Its weird... it's as though it becomes undefined only when the template file matches the filename which is what it should be.

Hoping this helps identify the issue more

**Comment by nachiketkallapur** [comment]
It worked  for me

    const nodemailer = require("nodemailer");
    const hbs = require("nodemailer-express-handlebars");

    const path = require('path');

    var transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "useremail",        //Add your email
        pass: "password",        //Add your password
      },
    });

    const handlebarOptions = {
      viewEngine: {
        extName: ".handlebars",
        partialsDir: path.resolve(__dirname, "templateViews"),
        defaultLayout: false,
      },
      viewPath: path.resolve(__dirname, "templateViews"),
      extName: ".handlebars",
    };

    transporter.use(
      "compile",
      hbs(handlebarOptions)
    );

    var mailOptions = {
      from: "username",
      to: req.body.email,
      subject: "Testing NodeMailer",
      template: "main",              //Any template stored in viewPath
    };

    transporter.sendMail(mailOptions, (error, info) => {
      if (error) {
        console.log(error);
      } else {
        res.send({
          status: "success",
          data: "Reset Link sent successfully",
        });
        console.log("Email sent: " + info.response);
      }
    });

**Comment by emarel** [comment]
> It worked for me
> 
> ```
> const nodemailer = require("nodemailer");
> const hbs = require("nodemailer-express-handlebars");
> 
> const path = require('path');
> 
> var transporter = nodemailer.createTransport({
>   service: "gmail",
>   auth: {
>     user: "useremail",        //Add your email
>     pass: "password",        //Add your password
>   },
> });
> 
> const handlebarOptions = {
>   viewEngine: {
>     extName: ".handlebars",
>     partialsDir: path.resolve(__dirname, "templateViews"),
>     defaultLayout: false,
>   },
>   viewPath: path.resolve(__dirname, "templateViews"),
>   extName: ".handlebars",
> };
> 
> transporter.use(
>   "compile",
>   hbs(handlebarOptions)
> );
> 
> var mailOptions = {
>   from: "username",
>   to: req.body.email,
>   subject: "Testing NodeMailer",
>   template: "main",              //Any template stored in viewPath
> };
> 
> transporter.sendMail(mailOptions, (error, info) => {
>   if (error) {
>     console.log(error);
>   } else {
>     res.send({
>       status: "success",
>       data: "Reset Link sent successfully",
>     });
>     console.log("Email sent: " + info.response);
>   }
> });
> ```

Appreciate you providing the code! I was able to get it to work with your implementation. For those that come across this issue it looks as though making it a async function with a callback caused some type of undefined issue. See code below for how the issue was caused. Thanks again @nachiketkallapur 

```
async function sendMail(user, callback) {
  var transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "userEmail",
      pass: "Password",
    },
  });

  const handlebarOptions = {
    viewEngine: {
      extName: ".handlebars",
      partialsDir: path.resolve(__dirname, "templateViews"),
      defaultLayout: false,
    },
    viewPath: path.resolve(__dirname, "templateViews"),
    extName: ".handlebars",
  };

  transporter.use(
    "compile",
    hbs(handlebarOptions)
  );

  let mailOptions = await transporter.sendMail({
    from: "username",
    to: 'req.body.email',
    subject: "Testing NodeMailer",
    template: "main"
  });

  let info = await transporter.sendMail(mailOptions);

  callback(info);
}
```

**Comment by emarel** [comment]
> It worked for me
> 
> ```
> const nodemailer = require("nodemailer");
> const hbs = require("nodemailer-express-handlebars");
> 
> const path = require('path');
> 
> var transporter = nodemailer.createTransport({
>   service: "gmail",
>   auth: {
>     user: "useremail",        //Add your email
>     pass: "password",        //Add your password
>   },
> });
> 
> const handlebarOptions = {
>   viewEngine: {
>     extName: ".handlebars",
>     partialsDir: path.resolve(__dirname, "templateViews"),
>     defaultLayout: false,
>   },
>   viewPath: path.resolve(__dirname, "templateViews"),
>   extName: ".handlebars",
> };
> 
> transporter.use(
>   "compile",
>   hbs(handlebarOptions)
> );
> 
> var mailOptions = {
>   from: "username",
>   to: req.body.email,
>   subject: "Testing NodeMailer",
>   template: "main",              //Any template stored in viewPath
> };
> 
> transporter.sendMail(mailOptions, (error, info) => {
>   if (error) {
>     console.log(error);
>   } else {
>     res.send({
>       status: "success",
>       data: "Reset Link sent successfully",
>     });
>     console.log("Email sent: " + info.response);
>   }
> });
> ```

Appreciate you providing the code! I was able to get it to work with your implementation. For those that come across this issue it looks as though making it a async function with a callback caused some type of undefined issue. I took @nachiketkallapur code and 

async function sendMail(user, callback) {
  var transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "userEmail",
      pass: "Password",
    },
  });

  const handlebarOptions = {
    viewEngine: {
      extName: ".handlebars",
      partialsDir: path.resolve(__dirname, "templateViews"),
      defaultLayout: false,
    },
    viewPath: path.resolve(__dirname, "templateViews"),
    extName: ".handlebars",
  };

  transporter.use(
    "compile",
    hbs(handlebarOptions)
  );

  let mailOptions = await transporter.sendMail({
    from: "username",
    to: 'req.body.email',
    subject: "Testing NodeMailer",
    template: "main"
  });

  let info = await transporter.sendMail(mailOptions);

  callback(info);
}

**Comment by nachiketkallapur** [comment]
@emarel Do you whether can we pass any argument to the handlebars file that is rendered in the above code? (I mean passing some dynamic values to handlebars email template from above configuration)

**Comment by emarel** [comment]
> @emarel Do you whether can we pass any argument to the handlebars file that is rendered in the above code? (I mean passing some dynamic values to handlebars email template from above configuration)

Yep, very easy to do. All you need to do is add a context object in the mailOptions object

 ```
 var mailOptions = {
   from: "username",
    to: 'req.body.email',
    subject: "Testing NodeMailer",
    template: "main"
    context: {
      to: recipientName,
      from: senderName,
      value: inputValue
    }
  };
```

In the handlebars file you can access the variable with {{value}}

**Comment by moongl4de** [comment]
@emarel @nachiketkallapur could you take a look at this and see what I'm doing wrong? 

I implemented your code but still getting the -4058 error. Any help would be awesome!

```
const nodemailer = require("nodemailer");
const hbs = require("nodemailer-express-handlebars");
const express = require("express");
const app = express();
const port = 3000;
var path = require("path");

var transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "myemail, //Add your email
    pass: "mypassword", //Add your password
  },
});

const handlebarOptions = {
  viewEngine: {
    extName: ".handlebars",
    partialsDir: path.resolve(__dirname, "views"),
    defaultLayout: false,
  },
  viewPath: path.resolve(__dirname, "views"),
  extName: ".handlebars",
};

transporter.use("compile", hbs(handlebarOptions));

var mailOptions = {
  from: "emailhere",
  to: "emailhere",
  subject: "Testing NodeMailer",
  template: "main", //Any template stored in viewPath
};

transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    console.log(error);
  } else {
    res.send({
      status: "success",
      data: "Reset Link sent successfully",
    });
    console.log("Email sent: " + info.response);
  }
});

app.listen(port, () => {
  console.log(
    `Server listening at http://localhost:${port}`
  );
});


```

**Comment by nachiketkallapur** [comment]
Thanks @emarel  for your reply. I had searched more than a week for that before your response

**Comment by nachiketkallapur** [comment]
@alexgignilliat  I tried your code. It's working in my system.

**Comment by moongl4de** [comment]
@nachiketkallapur thanks for the reply! So, I've got it sending an email now without an error, but it's a blank email. None of my handlebars is being sent. Any ideas would be much appreciated!!

**Comment by nachiketkallapur** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>A Simple Responsive HTML Email</title>
  <style type="text/css">
  body {margin: 0; padding: 0; min-width: 100%!important;}
  img {height: auto;}
  .content {width: 100%; max-width: 600px;}
  .header {padding: 40px 30px 20px 30px;}
  .innerpadding {padding: 30px 30px 30px 30px;}
  .borderbottom {border-bottom: 1px solid #f2eeed;}
  .subhead {font-size: 15px; color: #ffffff; font-family: sans-serif; letter-spacing: 10px;}
  .h1, .h2, .bodycopy {color: #153643; font-family: sans-serif;}
  .h1 {font-size: 33px; line-height: 38px; font-weight: bold;}
  .h2 {padding: 0 0 15px 0; font-size: 24px; line-height: 28px; font-weight: bold;}
  .bodycopy {font-size: 16px; line-height: 22px;}
  .button {text-align: center; font-size: 18px; font-family: sans-serif; font-weight: bold; padding: 0 30px 0 30px;}
  .button a {color: #ffffff; text-decoration: none;}
  .footer {padding: 20px 30px 15px 30px;}
  .footercopy {font-family: sans-serif; font-size: 14px; color: #ffffff;}
  .footercopy a {color: #ffffff; text-decoration: underline;}

  @media only screen and (max-width: 550px), screen and (max-device-width: 550px) {
  body[yahoo] .hide {display: none!important;}
  body[yahoo] .buttonwrapper {background-color: transparent!important;}
  body[yahoo] .button {padding: 0px!important;}
  body[yahoo] .button a {background-color: #e05443; padding: 15px 15px 13px!important;}
  body[yahoo] .unsubscribe {display: block; margin-top: 20px; padding: 10px 50px; background: #2f3942; border-radius: 5px; text-decoration: none!important; font-weight: bold;}
  }

  /*@media only screen and (min-device-width: 601px) {
    .content {width: 600px !important;}
    .col425 {width: 425px!important;}
    .col380 {width: 380px!important;}
    }*/

  </style>
</head>

<body yahoo bgcolor="#f6f8f1">
<table width="100%" bgcolor="#f6f8f1" border="0" cellpadding="0" cellspacing="0">
<tr>
  <td>
         
    <table bgcolor="#ffffff" class="content" align="center" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td bgcolor="#c7d8a7" class="header">
          <table width="70" align="left" border="0" cellpadding="0" cellspacing="0">  
            <tr>
              <td height="70" style="padding: 0 20px 20px 0;">
                <img class="fix" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/icon.gif" width="70" height="70" border="0" alt="" />
              </td>
            </tr>
          </table>
          
          <table class="col425" align="left" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 425px;">  
            <tr>
              <td height="70">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="subhead" style="padding: 0 0 0 3px;">
                      CREATING
                    </td>
                  </tr>
                  <tr>
                    <td class="h1" style="padding: 5px 0 0 0;">
                      Responsive Email Magic
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          
        </td>
      </tr>
      <tr>
        <td class="innerpadding borderbottom">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="h2">
                Welcome to our responsive email!
              </td>
            </tr>
            <tr>
              <td class="bodycopy">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempus adipiscing felis, sit amet blandit ipsum volutpat sed. Morbi porttitor, eget accumsan dictum, nisi libero ultricies ipsum, in posuere mauris neque at erat.
              </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td class="innerpadding borderbottom">
          <table width="115" align="left" border="0" cellpadding="0" cellspacing="0">  
            <tr>
              <td height="115" style="padding: 0 20px 20px 0;">
                <img class="fix" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/article1.png" width="115" height="115" border="0" alt="" />
              </td>
            </tr>
          </table>
          
          <table class="col380" align="left" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 380px;">  
            <tr>
              <td>
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="bodycopy">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempus adipiscing felis, sit amet blandit ipsum volutpat sed. Morbi porttitor, eget accumsan dictum, nisi libero ultricies ipsum, in posuere mauris neque at erat.
                    </td>
                  </tr>
                  <tr>
                    <td style="padding: 20px 0 0 0;">
                      <table class="buttonwrapper" bgcolor="#e05443" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td class="button" height="45">
                            <a href="#">Claim yours!</a>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          
        </td>
      </tr>
      <tr>
        <td class="innerpadding borderbottom">
          <img class="fix" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/wide.png" width="100%" border="0" alt="" />
        </td>
      </tr>
      <tr>
        <td class="innerpadding bodycopy">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempus adipiscing felis, sit amet blandit ipsum volutpat sed. Morbi porttitor, eget accumsan dictum, nisi libero ultricies ipsum, in posuere mauris neque at erat.
        </td>
      </tr>
      <tr>
        <td class="footer" bgcolor="#44525f">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" class="footercopy">
                &reg; Someone, somewhere 20XX<br/>
                <a href="#" class="unsubscribe"><font color="#ffffff">Unsubscribe</font></a> 
                <span class="hide">from this newsletter instantly</span>
              </td>
            </tr>
            <tr>
              <td align="center" style="padding: 20px 0 0 0;">
                <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="37" style="text-align: center; padding: 0 10px 0 10px;">
                      <a href="http://www.facebook.com/">
                        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/facebook.png" width="37" height="37" alt="Facebook" border="0" />
                      </a>
                    </td>
                    <td width="37" style="text-align: center; padding: 0 10px 0 10px;">
                      <a href="http://www.twitter.com/">
                        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/210284/twitter.png" width="37" height="37" alt="Twitter" border="0" />
                      </a>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    
    </td>
  </tr>
</table>
</body>
</html>

**Comment by nachiketkallapur** [comment]
Use the above main.handlebars for education purposes only. It's somebody's hardwork

**Comment by moongl4de** [comment]
@nachiketkallapur thank you for the info, but the issue is really that the data that should be passed into 'main.handlebars' from 'index.handlebars' doesn't show up in the email. I'm trying to dynamically populate the html before sending the email. (I know my code for handlebars itself is fine as I've tested it)

**Comment by nachiketkallapur** [comment]
Try saving your handlebars code.

Try with handlebars code from https://webdesign.tutsplus.com/articles/creating-a-simple-responsive-html-email--webdesign-12978

Also, note that few styling methods aren't compatible with the html parsers used by various mail services. Ex z-index, background-image etc.

**Comment by nachiketkallapur** [comment]
You can pass data from a .js file to .handlebars file by using the context property(as shown in the above code)

I have no idea on passing dynamic data from one .handlebars to another .handlebars file

**Comment by balakumararjunan** [comment]
@nachiketkallapur 
![nodeerr](https://github.com/yads/nodemailer-express-handlebars/assets/128220138/0f95d525-2d76-47f6-a1c5-18b664835a8f)
Still I am having error, can't resolve, kindly help
