### ISSUE TITLE
npm audit high severity vulnerabilities

### ISSUE THREAD

**Issue by mangos77** [yads/nodemailer-express-handlebars#53]
Al buscar vulnerabilidades con npm audit o intentar corregirlas con npm audit fix muestra:

express-handlebars  <5.3.1
Severity: **high**
Insecure template handling in Express-handlebars - https://github.com/advisories/GHSA-fr76-2wp8-fp92
**No fix available**
node_modules/nodemailer-express-handlebars/node_modules/express-handlebars
  nodemailer-express-handlebars  *
  Depends on vulnerable versions of express-handlebars
  node_modules/nodemailer-express-handlebars

2 high severity vulnerabilities

**** This no matter what I have installed:
"express-handlebars": "^6.0.2",

**Comment by BrunoRosendo** [comment]
Is it possible to get the version bumped? Thanks a lot

**Comment by DoStini** [comment]
@yads Can you also update the version in npm? Thanks

**Comment by yads** [comment]
Version 5.0.0 has been published that updates to latest express-handlebars
