### ISSUE TITLE
Unable to use custom extension for partials

### ISSUE THREAD

**Issue by nazmirket** [yads/nodemailer-express-handlebars#60]
When I use a custom file extension with settings below

```javascript
hbs({
		viewEngine: {
			extName: '.hbs',
			defaultLayout: false,
			partialsDir: PartialsDir,
		},
		viewPath: TemplateFolder,
		extName: '.hbs',
	})
```

My partials with ```.hbs``` extension  are not resolved. I think custom extension should also be applied to partials.

For anyone who is having the same problem, just name your partials with ```.handlebars```
 extension

**Comment by yads** [comment]
I believe this is an issue with express-handlebars. Please open an issue with that project.

**Comment by rosselpha** [comment]
i think this error is coming from nodemailer-express-handlebars----- Error: The partial header could not be found

**Comment by yads** [comment]
nodemailer-express-handlebars may be in the stack trace, but the error is
coming from further down the toolchain. This extension does not configure
partials. That is handled by your express-handlebars configuration which
you either instantiate directly or pass as the optionset `viewEngine`.
