### ISSUE TITLE
Text Template doesn't work

### ISSUE THREAD

**Issue by aqibgatoo** [yads/nodemailer-express-handlebars#64]
The presence of the `text_template` option doesn't work, only html is spewed out.

```
 const mailOptions = {
      from: 'something@soething.com',
      to:  'something@soething.com',
      bcc:  'something@soething.com',
      subject: 'test',
      template: 'email',
      text_template: 'text',
      context: {
        ...context,
      },
    };
```

"nodemailer": "^6.9.3",
"nodemailer-express-handlebars": "^6.1.0",

**Comment by yads** [comment]
What is the behaviour you're experiencing? Specifying `text_template` should generate a mail object with both `html` and `text` fields as per https://nodemailer.com/message/
