### ISSUE TITLE
can't render array of objects

### ISSUE THREAD

**Issue by marksaado** [yads/nodemailer-express-handlebars#65]
Hello there,

I'm trying to loop array of objects called reservation_items, this is my code:
{{#each reservation_items}}
        <p>
          <span>Item ID: {{this.itemId}}</span>
          <span>Quantity: {{this.value}}</span>
          <span>Item Price: {{this.itemPrice}}</span>
          <span>Item Name: {{this.name}}</span>
        </p>
      {{/each}}

- the context has other values like firstName, lastName... etc. all of them are working fine (I can see the real values in the email in my inbox) but that array (reservation_items)

 can you please help with that?
 
 thanks in advance

**Comment by yads** [comment]
Not really sure I can help. This package simply uses `express-handlebars` to generate the html, it doesn't do any processing of templates directly. This is likely an issue with your template, what's in `reservation_items`, or an issue with `express-handlebars` package
