### ISSUE TITLE
There is no default template

### ISSUE THREAD

**Issue by titsex** [yads/nodemailer-express-handlebars#66]
Hello! I have a problem, the plugin is looking for main.handlebars in the root of the project, and not in the folder I specified.

![The path to the views folder is specified](https://github.com/yads/nodemailer-express-handlebars/assets/61911688/d14b2e9d-c93a-4d32-b456-91014c2b29d3)

![Error, as it tries to open the main.handlebars template in the root of the project](https://github.com/yads/nodemailer-express-handlebars/assets/61911688/a677ce86-dca0-40eb-b21f-46560cc813e5)

I can also suggest adding the possibility of disabling the mandatory default template with the **defaultLayoyut: boolean** parameter

**Comment by milad2golnia** [comment]
I'm passing viewEngine option and it's ok:
```
hbs({
        viewEngine: {
          extname: '.handlebars',
          layoutsDir: './templates',
          defaultLayout: './yourDefaultTemplate',
          partialsDir: './templates',
        },
}
```

**Comment by yads** [comment]
This is likely an issue with how you're using express-handlebars. This plugin does not have a `defaultLayoyut` option.
