### ISSUE TITLE
Cannot find module './types'

### ISSUE THREAD

**Issue by A-Margaryan** [yads/nodemailer-express-handlebars#67]
Hi dear "nodemailer-express-handlebars" team, when I deployed my app, this problem with module "./types" in "express-handlebars/dist/index.js" occured.

Sep 20 04:00:10 PM  Error: Cannot find module './types'
Sep 20 04:00:10 PM  Require stack:
Sep 20 04:00:10 PM  - /opt/render/project/src/node_modules/express-handlebars/dist/index.js
Sep 20 04:00:10 PM  - /opt/render/project/src/node_modules/nodemailer-express-handlebars/lib/generator.js
Sep 20 04:00:10 PM  - /opt/render/project/src/node_modules/nodemailer-express-handlebars/lib/index.js
Sep 20 04:00:10 PM  - /opt/render/project/src/node_modules/nodemailer-express-handlebars/index.js

![image](https://github.com/yads/nodemailer-express-handlebars/assets/145031482/647d8bce-8cc1-413d-bd6b-e738d410ddf6)

**Comment by afiffanoor** [comment]
Hey, 
Have you figured out the issue?
Are you still facing this issue? Let me know 
Thanks

**Comment by yads** [comment]
Without more details I'm not sure I can help with this.
